name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # required to push to CD repo

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # -------------------- Compile & Syntax Check --------------------
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # LTS recommended

      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +

  # -------------------- Gitleaks Secret Scan --------------------
  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Run Gitleaks
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  # -------------------- Trivy Filesystem Scan --------------------
  trivy_fs_scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

  # -------------------- Build & Push Docker Backend --------------------
  build_backend_docker_image_and_push:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: in30minthing
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (backend)
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            in30minthing/backend:latest
            in30minthing/backend:${{ env.IMAGE_TAG }}

  # -------------------- Build & Push Docker Frontend --------------------
  build_frontend_docker_image_and_push:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: in30minthing
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (frontend)
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            in30minthing/frontend:latest
            in30minthing/frontend:${{ env.IMAGE_TAG }}

  # -------------------- Trivy Image Scan --------------------
  trivy_image_scan:
    runs-on: ubuntu-latest
    needs:
      - build_backend_docker_image_and_push
      - build_frontend_docker_image_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan backend image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: in30minthing/backend:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: in30minthing/frontend:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

  # -------------------- Update CD Repo --------------------
  update_cd_repo:
    runs-on: ubuntu-latest
    needs: trivy_image_scan
    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v4
        with:
          repository: khushboo-sah/3-Tier-GitOps-CD
          ref: main
          token: ${{ secrets.CD_REPO_TOKEN }}
          path: cd

      - name: Install yq
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq
          sudo install yq /usr/local/bin/yq

      - name: Bump images in manifests
        working-directory: cd
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          # Update Deployment images (backend)
          yq -i '(. | select(.kind=="Deployment") | .spec.template.spec.containers[] | select(.name=="backend")).image = "in30minthing/backend:" + strenv(IMAGE_TAG)' k8s-prod/backend.yaml

          # Update Deployment images (frontend)
          yq -i '(. | select(.kind=="Deployment") | .spec.template.spec.containers[] | select(.name=="frontend")).image = "in30minthing/frontend:" + strenv(IMAGE_TAG)' k8s-prod/frontend.yaml

      - name: Commit & push to CD repo
        working-directory: cd
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git add -A
            git commit -m "bump images to ${IMAGE_TAG}"
            git push origin main
